<?php

namespace ValehAsadli\Kafka;

use Illuminate\Support\ServiceProvider;
use ValehAsadli\Kafka\Connectors\KafkaQueueConnector;

class KafkaQueueServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        $this->app['queue']->addConnector('kafka', fn() => new KafkaQueueConnector());
    }
}